AlexPikalov/cdrs

- src/authenticators.rs
- src/client.rs
> Implement Drop for session

- README.md
- src/client.rs
> Implement get_options method of CDRS instance

- src/frame/frame_result.rs
> Implement schema change function and aggregation

- README.md
- examples/read_table_into_struct.rs
- src/client.rs
- src/error.rs
- src/types/list.rs
- src/types/map.rs
- src/types/mod.rs
- src/types/rows.rs
- src/types/udt.rs
> Refactor cdrs-to-rust mappers

- README.md
- examples/create_table.rs
- examples/read_table_into_struct.rs
- examples/simple.rs
- src/client.rs
- src/frame/frame_auth_response.rs
- src/frame/frame_execute.rs
- src/frame/frame_options.rs
- src/frame/frame_prepare.rs
- src/frame/frame_query.rs
- src/frame/frame_startup.rs
- src/frame/mod.rs
- src/frame/parser.rs
> Query warnings implementation

- examples/read_table_into_struct.rs
- src/types/rows.rs
i have added serialization of cassandra int to `i64` on rust side
> Rust panicking While executing example read_table_into_struct #34

- README.md
- examples/connection_pool.rs
- examples/prepare_execute.rs
- examples/read_table_into_struct.rs
- examples/simple.rs
- src/client.rs
- src/connection_manager.rs
- src/consistency.rs
- src/frame/frame_execute.rs
- src/frame/frame_query.rs
- src/frame/frame_response.rs
- src/frame/frame_result.rs
- src/lib.rs
- src/query.rs
* `Query` and builders extracted into a separate module `cdrs::query`
* Readme updated
> Extract query

- examples/batch_queries.rs
- src/client.rs
- src/frame/frame_batch.rs
- src/frame/frame_prepare.rs
- src/frame/mod.rs
- src/query.rs
* Add batch queries functionality
Provides #39
> Add batch queries functionality

- examples/simple.rs
- examples/simple_with_auth.rs
- src/authenticators.rs
- src/client.rs
- tests/authenticators.rs
if the server doesn't provide username/pwd auth; we need a default no-authentication for that purpose. In case the server requests for password and client never provided one; the client should return an Error back
> Create EmptyAuthenticator 

- src/authenticators.rs
- src/client.rs
- src/connection_manager.rs
- src/frame/frame_batch.rs
- src/frame/frame_execute.rs
- src/frame/frame_options.rs
- src/frame/frame_prepare.rs
- src/frame/frame_ready.rs
- src/frame/frame_startup.rs
- src/query.rs
- src/transport.rs
- src/transport_ssl.rs
- src/types/list.rs
- src/types/map.rs
- src/types/rows.rs
- src/types/udt.rs
> Derive debug for all structs

- src/frame/events.rs
- src/frame/frame_auth_challenge.rs
- src/frame/frame_auth_response.rs
- src/frame/frame_auth_success.rs
- src/frame/frame_authenticate.rs
- src/frame/frame_batch.rs
- src/frame/frame_error.rs
- src/frame/frame_execute.rs
- src/frame/frame_options.rs
- src/frame/frame_prepare.rs
- src/frame/frame_query.rs
- src/frame/frame_ready.rs
- src/frame/frame_register.rs
- src/frame/frame_response.rs
- src/frame/frame_result.rs
- src/frame/frame_startup.rs
- src/frame/frame_supported.rs
- src/frame/mod.rs
- src/types/data_serialization_types.rs
- src/types/list.rs
Cargo Clippy comments incorporated
> Cargo Clippy comments incorporated

- src/client.rs
- src/compression.rs
- src/frame/frame_startup.rs
- src/frame/frame_supported.rs
Tests for following frame sub-modules:
* frame_startup
* frame_supported
> Create tests for frames

- src/frame/frame_auth_challenge.rs
- src/frame/frame_auth_success.rs
- src/frame/frame_ready.rs
Tests for:
* frame_ready
* frame_auth_challenge
* frame_auth_success
> Frame tests

- .travis.yml
- README.md
- src/frame/frame_result.rs
- src/transport.rs
- tests/create_ks_and_table.rs
- tests/lib.rs
- there was a code change for thread panicking.
- added cassandra as part of travis; now you can safely write integration test cases; I have written for create keyspace ; create table ; drop keyspace ;
- added a single doc-test; we have to improve a lot on this
- now we have unit-tests, integration-test and doc-tests running.
> Thread Panicking + Cassandra installed on travis

- src/frame/frame_auth_response.rs
- src/frame/frame_query.rs
- src/query.rs
> Fix variables binding

- src/types/value.rs
- tests/create_insert_table.rs
I have added into Trait for value, we have to create Into Traits for all primitive types so that all converting into value is seamless
> added into trait for value

- README.md
> added gitter

- src/query.rs
* unnecessary allocations was removed from query builders
* added tests for query builders
> Query builders optimisation and tests

- examples/prepare_execute.rs
- src/client.rs
- src/frame/frame_execute.rs
- src/frame/frame_response.rs
- src/frame/frame_result.rs
- src/frame/mod.rs
- tests/create_insert_table.rs
> Change execute signature

- examples/all.rs
- src/frame/frame_batch.rs
- src/frame/frame_query.rs
- src/frame/frame_result.rs
- src/frame/frame_startup.rs
- src/query.rs
- src/types/data_serialization_types.rs
- src/types/list.rs
- src/types/map.rs
- src/types/mod.rs
- src/types/rows.rs
- src/types/udt.rs
- src/types/value.rs
* `Into<Value>` implementations for easy type conversion
* fix UDT parser
* add example with illustration how to work with different types
> To value conversion

- examples/all.rs
- src/types/mod.rs
- src/types/value.rs
* Into<Value> for float numbers and related Apache Cassandra types
* add related examples
> Add into Value implementators for float numbers

- src/types/mod.rs
- tests/create_insert_table.rs
* fix `Int::from_cursor`
* fix `ShortInt::from_cursor`
* fix `CBytes::from_cursor` for null and not-set values
Fixes #97 and #96
> Fix parsing negative integers

- src/error.rs
- src/types/rows.rs
- src/types/udt.rs
- tests/create_insert_table.rs
Noticed that when inserting/reading data that contains NULL causes
> fatal runtime error: out of memory
I reproduced issue below. Couldn't trace error due to lack of details.
cc @AlexPikalov @harrydevnull
> Inserting null causes runtime error

- src/client.rs
- src/compression.rs
> Make CDRS and connection derive Eq and Ord

- src/compression.rs
This makes cdrs compatible with error-chain.
> Use upstream error types in CompressionError

- examples/all.rs
It took me a while to figure out that calling `into()` on a `Vec<u8>` in order to convert it into `Bytes` doesn't work as I expected.
`impl<T: Into<Bytes> + Clone + Debug> From<Vec<T>> for Bytes` exists but I'm not sure what it does exactly.
> Add blob example

- Cargo.toml
- src/cluster.rs
- src/lib.rs
* Draft version of load balancer and cluster support
> Load balancer draft version

- examples/cluster.rs
- src/client.rs
- src/cluster.rs
- src/error.rs
- src/transport.rs
- tests/build-cluster.sh
* Add cluster example
* Create bash script to build Cassandra cluster
Provides #37
> Cluster support

- tests/create_insert_table.rs
- tests/crud_operations.rs
> More e2e tests

- src/types/data_serialization_types.rs
* implement tests for `decode_x` functions
> Implement test for deserializators

- src/types/data_serialization_types.rs
* add test for `as_rust` macro
> Add tests for decoders

- .travis.yml
- examples/all.rs
- examples/batch_queries.rs
- examples/cluster.rs
- examples/connection_pool.rs
- examples/prepare_execute.rs
- examples/server_events.rs
- src/authenticators.rs
- src/client.rs
- src/cluster.rs
- src/compression.rs
- src/consistency.rs
- src/frame/frame_query.rs
- src/frame/frame_result.rs
- src/frame/mod.rs
- src/query.rs
- src/transport.rs
- src/types/data_serialization_types.rs
- src/types/list.rs
- src/types/mod.rs
- src/types/rows.rs
- src/types/udt.rs
- src/types/value.rs
- tests/create_insert_table.rs
- tests/crud_operations.rs
- tests/simple_connect.rs
the rustfmt has been changed and it has been incorporated back to the project.
right now I have enabled force installation of rustfmt in travis so builds might be slightly slower. once the dust settles down we shall enable the caching of cargo rust fmt
> updated to the latest rustfmt and clippy warnings

- .travis.yml
now that travis has got the latest version of rustfmt; rolling back the caching mechanism of cargo so that builds are bit faster
> rolled back the caching mechanism of cargo

- README.md
- examples/all.rs
- examples/batch_queries.rs
- examples/prepare_execute.rs
- examples/read_table_into_struct.rs
- examples/simple.rs
- src/client.rs
- src/consistency.rs
- src/events.rs
- src/frame/events.rs
- src/frame/frame_auth_challenge.rs
- src/frame/frame_auth_success.rs
- src/frame/frame_authenticate.rs
- src/frame/frame_error.rs
- src/frame/frame_event.rs
- src/frame/frame_query.rs
- src/frame/frame_response.rs
- src/frame/frame_result.rs
- src/frame/frame_supported.rs
- src/frame/mod.rs
- src/frame/parser.rs
- src/lib.rs
- src/types/data_serialization_types.rs
- src/types/list.rs
- src/types/mod.rs
- tests/create_insert_table.rs
- tests/crud_operations.rs
fixes #45 
* most of `unwrap()` calls were removed
> Revise unwraps

- src/frame/events.rs
- src/frame/frame_error.rs
- src/frame/frame_result.rs
> Rid of unreachable

- .travis.yml
- src/cluster.rs
- src/connection_manager.rs
- src/consistency.rs
- src/frame/events.rs
- src/frame/frame_query.rs
- src/frame/frame_response.rs
- src/frame/frame_result.rs
> More CLippy comments

- Cargo.toml
- examples/all.rs
- src/frame/frame_result.rs
- src/frame/mod.rs
- tests/crud_operations.rs
Provides a backward compatibility with [version 3 protocol](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v3.spec)
> Add protocol version feature

- src/cluster.rs
> Fix round robin next value evaluation

- README.md
- src/macros.rs
- src/types/rows.rs
> Implement IntoRustByIndex and ByIndex for Row

- Cargo.toml
Updates uuid to 0.5 matching many other libraries (serde, postgres)
> feat: update uuid to 0.5

- .travis.yml
- src/client.rs
- src/frame/parser.rs
> Handle empty frames properly

- Cargo.toml
> Upgrade to snap v0.2

- src/cluster.rs
- src/frame/parser.rs
- src/transport.rs
> Add buferization to Tcp stream reading

- src/types/value.rs
- tests/native_types.rs
Added Clone to Bytes and created a test for blob that stores and retrieves a HashMap
> deriving Clone for Bytes to make Hashmap<T, Bytes> work

- examples/all.rs
- src/macros.rs
- src/types/blob.rs
- src/types/data_serialization_types.rs
- src/types/list.rs
- src/types/map.rs
- src/types/mod.rs
- src/types/rows.rs
- src/types/tuple.rs
- src/types/udt.rs
- src/types/value.rs
- tests/collection_types.rs
- tests/native_types.rs
- tests/tuple_types.rs
- type-mapping.md
> Create Blob type to present Cassandra blob

- Cargo.toml
- changelog.md
Fix #177 
bump version to 1.1.0
> Create changelog. Bump version 1.1.0

- examples/.gitignore
- src/transport.rs
> Don't rely on failed connection inner address during re-connection

- src/client.rs
- src/connection_manager.rs
- src/frame/parser.rs
- src/transport.rs
- src/types/mod.rs
It provides connection manager performance optimization.
> Fix health check performance

- .travis.yml
- tests/collection_types.rs
- tests/create_insert_table.rs
- tests/keyspace.rs
- tests/native_types.rs
- tests/simple_connect.rs
- tests/tuple_types.rs
- tests/user_defined_types.rs
This disable makes build possible until #198 fixed (which is blocked by https://issues.apache.org/jira/browse/CASSANDRA-14173)
> Temporary disable ci e2e

- .travis.yml
> Enable e2e tests in CI

- Cargo.toml
> fix(Cargo.toml): fix uuid dependency version

- src/frame/parser.rs
- src/types/mod.rs
> Fix protocol corruption by using `read_exact`

- examples/batch_queries.rs
> Provide batch with values example

- .travis.yml
- src/types/data_serialization_types.rs
- src/types/decimal.rs
- src/types/mod.rs
- src/types/value.rs
- tests/native_types.rs
Fixes #236 
It provides a fix for decimal numbers encoding and decoding.
> fix(decimal): Fix decimal encoding and decoding

- src/cluster/ssl_connection_pool.rs
- src/cluster/tcp_connection_pool.rs
> fix(conneciton-pool): fix wrong has_broken condition

- Cargo.toml
> Update byteorder version

- type-mapping.md
> doc: fix counter to Rust type mapping

- examples/crud_operations.rs
- src/authenticators.rs
> feat: Create StaticPasswordAuthenticator

- Cargo.toml
- src/cluster/config_ssl.rs
> fix: config ssl unexpected token

- src/query/batch_executor.rs
- src/query/exec_executor.rs
- src/query/mod.rs
- src/query/prepare_executor.rs
- src/query/query_executor.rs
- src/query/query_params_builder.rs
- src/query/utils.rs
> refactor: create query utils to rid of logic duplication

- src/error.rs
- src/types/data_serialization_types.rs
> fix: update UUID version

- examples/README.md
This is also to solve the issue #297.
> Added a new example.

- examples/crud_operations.rs
- src/cluster/ssl_connection_pool.rs
- src/cluster/tcp_connection_pool.rs
- tests/common/mod.rs
> fix: fix IP parsing error when using hostname

- README.md
> In README file, added link to RUST and Scylla lesson

- Cargo.toml
- src/types/value.rs
Makes testing inside the (derive) crate easier
> Added derived partialeq trait to Value and ValueType

- src/cluster/session.rs
- src/events.rs
> Derive debug implementations for EventStreamNonBlocking and Session.

- src/cluster/generic_connection_pool.rs
- src/cluster/session.rs
- src/cluster/ssl_connection_pool.rs
- src/cluster/tcp_connection_pool.rs
- src/events.rs
- src/load_balancing/round_robin.rs
- src/types/list.rs
> Derive implementations of Debug for various types, and derive IntoRustByIndex for Vec<Timespec>

- src/query/prepare_executor.rs
These two new methods return the raw prepared query result which has
additional information like column types which can be useful in
certain applications.
> Add prepare_raw and prepare_raw_tw methods

- src/query/utils.rs
The `send_frame` function did use `write` method to send out
frame data. The method actually writes just a portion of the data provided
(usually first 16K). The rest was not written and got lost.
That caused Cassandra node peer send no reply waiting for more frame data,
which in turn led to `send_frame` hanging infinitely.
The `write_all` method has to be used instead.
> Fix query execution lock-up for large frames.
