AlexPikalov/cdrs

.gitignore
src/transport_ssl.rs

the unwrap call on transport_ssl.rs was panic-ing the rust thread #43 
I have replaced the unwrap call with error handling so that thread doesn't panic.
I have left transformations as comments in the code itself

#43 the unwrap call has been replaced with converting into error

---

examples/batch_queries.rs
examples/connection_pool.rs
examples/create_table.rs
examples/prepare_execute.rs
examples/read_table_into_struct.rs
examples/server_events.rs
examples/simple.rs
examples/simple_with_auth.rs

* adopt all examples to not crush when running `cargo test --all-features` or `cargo run --examples example-name --features ssl` (implementations will be provided in next PR)
fixes #63 (1)

Adopt examples to run with ssl and all features

---

src/frame/frame_batch.rs
src/frame/frame_query.rs
src/query.rs
src/types/data_serialization_types.rs

Use i64 for timestamp as referenced in https://github.com/AlexPikalov/cdrs/blob/master/type-mapping.md

Use i64 for timestamp

---

Cargo.toml

Dual licensing MIT/Apache-2.0
fixes #84

Dual license. MIT/Apache-2.0

---

src/types/data_serialization_types.rs
src/types/map.rs
src/types/mod.rs
src/types/rows.rs

1.  "Return" `Result`s from `as_rust!` instead of using `unwrap()` and `unreachable!`.
2. Implement `IntoRustByName<_> for Row` using a new macro `row_into_rust_by_name!`.
`row_into_rust_by_name!` uses `as_rust!` and the implementations change a bit, although I think the new behavior is more accurate.
But it still leaves a problem. `get_by_name()` returns `Option<Result<_>>`. `None` if the column can't be found and `Some(Err(_))` if the conversion fails. It also returns a custom error if the value is empty (except for blobs) and it doesn't handle `null` values explicitly. It would be nice if an `Option` could be returned, that is `None` in case of a `null` value.
Maybe we could change the return type to `Result<Option<_>>` and return an error if the column can't be found. I'm not sure …

Proper error handling in as_rust! and new macro for IntoRustByName

---

.gitignore
tests/crud_operations.rs

the tests were failing when using using cassandra 2.2
`Non frozen collections and user defined types on Cassandra 2.1.8`
I have added the frozen on the cassandra create schema time

added backward compatibility on tests for cassandra 2.2

---

src/transport.rs
src/types/data_serialization_types.rs

* add method `set_timeout` to `CDRSTransport` trait
* implement `set_timeout` method for `TransportTcp`
* implement `set_timeout` method for `TransportTls`

Transport timeouts

---

Cargo.toml
examples/all.rs
src/lib.rs
src/macros.rs
src/types/rows.rs
src/types/value.rs
tests/crud_operations.rs

This makes it easy to store and retrieve time-stamps.
Time-stamps are stored as i64 according to the v4 protocol specs.

Support timestamps using time::Timespec

---

.travis.yml
examples/all.rs
src/macros.rs
src/types/data_serialization_types.rs
src/types/list.rs
src/types/map.rs
src/types/mod.rs
src/types/rows.rs
src/types/udt.rs
tests/create_insert_table.rs
tests/crud_operations.rs
tests/simple_connect.rs

Fixes #94
This PR allows to simplify such "non-primitive" Cassandra types mapping as `list` (which is equivalent to `set` in CDRS), `map` and `udt`.
**Before** (for `Vec<i32>`): 
```rust
let list: List = row.get_by_name("int_list")
.unwrap()
.unwrap(); // this intermediate variable used to be required
let vector: Vec<i32> = list.as_rust().unwrap();
```
**After**: 
```rust
let vector: Vec<i32> = row.get_by_name::<List>("int_list")
.unwrap()
.unwrap()
.as_rust()
.unwrap();
```
**Breaking change**.
**Before**: 
```rust
pub trait AsRust<T> {
fn as_rust(&self) -> CDRSResult<T>;
```
**After**:
```rust
pub trait AsRustType<T> {
fn as_rust_type(&self) -> CDRSResult<T>;
}
pub trait AsRust {
fn as_rust<T>(&self) -> CDRSResult<T>
}
```
**New trait**:
```rust
pub trait ByName {
fn by_name<R>(&self, …
```

Modify AsRust, AsRustByName traits

---

README.md
examples/all.rs
examples/read_table_into_struct.rs
examples/simple.rs
src/authenticators.rs
src/frame/frame_auth_challenge.rs
src/macros.rs
src/types/data_serialization_types.rs
src/types/list.rs
src/types/mod.rs
src/types/rows.rs
src/types/udt.rs
tests/create_insert_table.rs
tests/crud_operations.rs

Fixes #111 
**Breaking changes**:
Before:
```rust
pub trait AsRustType<T> {
fn as_rust_type(&self) -> CDRSResult<T>;
}
pub trait AsRust {
fn as_rust<R>(&self) -> CDRSResult<R> where Self: AsRustType<R>;
}
pub trait IntoRustByName<R> {
fn get_by_name(&self, name: &str) -> Option<CDRSResult<R>>;
}
pub trait ByName {
fn by_name<R>(&self, name: &str) -> Option<CDRSResult<R>> where Self: IntoRustByName<R>;
}
```
**After**:
```rust
pub trait AsRustType<T> {
fn as_rust_type(&self) -> CDRSResult<Option<T>>;
// NEW: as non-optional Rust type
fn as_r_type(&self) -> CDRSResult<T>;
}
pub trait AsRust {
fn as_rust<R>(&self) -> CDRSResult<Option<R>> where Self: AsRustType<R>;
// NEW: as non-optional Rust type
fn as_r_rust<T>(&self) -> CDRSResult<T> where Self: AsRustType<T>;
}
/// Should be used to …
```

New into rust conversion

---

Cargo.toml

`v5` feature is temporary disabled as version 5 protocol is in beta.
Probably it makes sense to start its development when the protocol is stable.

Disable v5 feature until it's implemented

---

src/cluster.rs

The current impl for the LoadBalancerStrategy::Random has risk of overflow (and does so often) This reworks it to avoid the multiplication.

refactor cluster::rnd_idx to avoid overflow

---

README.md
src/lib.rs

Related to #185 
But signature has been changed to following
```rust
pub trait IntoCDRSValue {
fn into_cdrs_value(self) -> Value;
}
```

Into cdrs bytes trait

---

src/consistency.rs

This makes it easier to pass around by value a Consistency rather than
forcing a clone(). This is fine as the size of a Consistency value is
a single machine word typically.

Consistency derives Copy

---

examples/batch_queries.rs
examples/cluster.rs
examples/connection_pool.rs
examples/create_table.rs
examples/prepare_execute.rs
examples/read_table_into_struct.rs
examples/simple.rs
examples/simple_with_auth.rs
src/client.rs
tests/collection_types.rs
tests/common/mod.rs
tests/create_insert_table.rs
tests/keyspace.rs
tests/native_types.rs
tests/simple_connect.rs
tests/tuple_types.rs
tests/user_defined_types.rs

As the title says this renames Session to InternalSession, then provides a RefCell wrapper for Session that allows for external mutability. This allows, much like the postgres crate, an immutable shared reference to be used by crate users.
For comparison:
https://github.com/sfackler/rust-postgres/blob/master/postgres/src/lib.rs#L951
This fixes #201 
Notably when running tests or compiling code rustc will warn about not needing mut anymore, but no breaking changes are required for this!

Use a RefCell to provide external immutability for Session

---

Cargo.toml

Hey
Updating this crate to 0.6 since the new release is out. There are no further changes required.

Updating uuid to 0.6.1

---

CONTRIBUTORS.md
Cargo.toml
src/error.rs
src/types/data_serialization_types.rs

This updates uuid to 0.7.
The release contains some breaking changes and those have changes have been made for this crate. 
This is a breaking change for your crate and luckilly found this before you issued a major 2.0 stable release :smile:

Update uuid to 0.7

---

src/load_balancing/mod.rs
src/load_balancing/round_robin_sync.rs
src/load_balancing/single_node.rs

Switch to a blocking mutex lock to prevent "Unable to ge transport" error in multi threaded applications.
references issue #230

Switch to blocking mutex lock

---

src/types/rows.rs

Needed to take some vector element without breaking an vector of rows
(also needed since `try_from_row` method can't work with refs)
(also please tell if there is any communication channel, I had few additional questions)

Add possibility to clone Row

---

src/frame/frame_error.rs

It fixes an un prepared query error parser

fix(Error Frame): Fix UnpreparedError::id type

---

examples/paged_query.rs
rustfmt.toml
src/cluster/mod.rs
src/cluster/pager.rs

I had to implement pagination for stateless connections (HTTP) and your API does not allow to pull the internal state of the pager. So, I have injected the pager state when you ask for execute a new query and obtain the same state from the pager.
PS: I am not very comfortable with Rust, if you see that I have a mistake, please let me know. 
Thanks.

Pager for stateless executions

---

examples/README.md
examples/insert_collection.rs

This test is a copy of the `crud_operation` example, however I've changed the table used for a new one named `test_ks.collection_table`.  
This example shows how to append/prepend to lists, append to maps and append to sets. I've used [this](https://docs.datastax.com/en/archived/cql/3.3/cql/cql_using/useInsertList.html) as a reference to learn how to do it.

doc: Add an example for pushing items to a collection Fixes #286

---

src/cluster/tcp_connection_pool.rs
src/frame/frame_auth_response.rs

> Only one thing. I like the original idea to have a separate structure for each type of body. So if we can agree that this already contains bytes then we can modify new_req_auth_response in following way:
Yes, I totally agree.
I made those changes and have tested, I have to add the uuid dep #298 and have removed it for this PR.
If it is anything wrong, please tell me :+1: 
thank you once more.

#296 Removed the extra 4 bytes from the auth response

---

src/authenticators.rs

This is another fix on removing compile warnings.

(fix) warnings on deprecated api

---

src/frame/traits.rs

I will also this to some derive macro's, since some of the derive macro's are not namespaced enough (the try_from_row.rs derive macro expects a `Row`, but it should be` cdrs::types::rows::Row`). This adds more consistency to this crate and the derive crate.
I will add namespacing to the derive crate if https://github.com/AlexPikalov/cdrs-helpers-derive/pull/6 is merged

Inlined imports

---

Cargo.toml
src/cluster/config_rustls.rs
src/cluster/mod.rs
src/cluster/rustls_connection_pool.rs
src/lib.rs
src/transport.rs

This introduces `rust-tls` features with `rustls` and `webpki`
For simplicity sake user is the one who configures rustls as it is rather complicated.
I feel like it would be better to come up with some generic for transport layer, but I decided for now we can go with code duplication
Closes #315

Introduce rust-tls feature
